version: 2.1

jobs:
  build:
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      # Run a step to print what branch our code base is on.
      - run: # test what branch we're on.
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      # Run another step, the same as above; note that you can
      # invoke environment variable without curly braces.
      # prints: XXXXXXX

      - run:
          name: "What tag am I on?"
          command: echo ${CIRCLE_TAG}  # prints: XXXXXXX


workflows:
  version: 2.1

  build_and_deploy_staging:
    jobs:
      - build:
          filters:
            branches:
              only: /^release-.*/

  build_and_deploy_production:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
